{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "molecular-audit-core.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molecular-audit-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.console.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "molecular-audit-core.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: console
  ports:
    - name: http
      port: {{ .Values.console.service.port }}
      targetPort: {{ .Values.console.service.targetPort }}
{{- end }}
