{{- if .Values.console.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "molecular-audit-core.fullname" . }}-console
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molecular-audit-core.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "molecular-audit-core.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "molecular-audit-core.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: console
      {{- if eq .Values.storage.type "gcs" }}
      annotations:
        gke-gcsfuse/volumes: "true"
      {{- end }}
    spec:
      serviceAccountName: {{ include "molecular-audit-core.serviceAccountName" . | quote }}
      containers:
        - name: console
          image: "{{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PORT
              value: {{ .Values.console.service.targetPort | quote }}
            - name: K8S_INCLUSTER
              value: "true"
            # Marketplace installs should not require an extra UI token to run in-cluster actions.
            # If you expose this service publicly, set this to "false" and configure K8S_API_TOKENS.
            - name: K8S_AUTH_DISABLED
              value: "true"
            - name: GBX_STORAGE_TYPE
              value: {{ .Values.storage.type | quote }}
            - name: GBX_GCS_BUCKET
              value: {{ .Values.storage.gcs.bucket | quote }}
            - name: GBX_GCS_MOUNT_PATH
              value: {{ .Values.storage.gcs.mountPath | quote }}
            - name: GBX_INPUT_ROOT
              value: {{ .Values.config.inputPath | quote }}
            - name: GBX_OUTPUT_ROOT
              value: {{ .Values.config.outputPath | quote }}
            - name: GBX_RUNNER_IMAGE
              {{- if .Values.image.digest }}
              value: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
              {{- else }}
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              {{- end }}
            - name: GBX_RUNNER_SERVICE_ACCOUNT
              value: {{ include "molecular-audit-core.serviceAccountName" . | quote }}
            - name: GBX_APP_FULLNAME
              value: {{ include "molecular-audit-core.fullname" . | quote }}
            {{- if eq .Values.storage.type "pvc" }}
            - name: GBX_DATA_PVC
              value: {{ include "molecular-audit-core.fullname" . }}-data
            {{- end }}
            - name: MARKETPLACE_REPORTING_SECRET
              value: {{ .Values.marketplace.reportingSecret | quote }}
            - name: UBBAGENT_ENABLED
              value: {{ .Values.ubbagent.enabled | quote }}
            - name: UBBAGENT_IMAGE
              value: "{{ .Values.ubbagent.image.repository }}:{{ .Values.ubbagent.image.tag }}"
            - name: UBBAGENT_PULL_POLICY
              value: {{ .Values.ubbagent.image.pullPolicy | quote }}
            - name: UBBAGENT_LOCAL_PORT
              value: {{ .Values.ubbagent.localPort | quote }}
            - name: UBBAGENT_METRIC_NAME
              value: {{ .Values.ubbagent.metricName | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.console.service.targetPort }}
          volumeMounts:
            - name: mol-audit-data
              mountPath: {{ if eq .Values.storage.type "gcs" }}{{ .Values.storage.gcs.mountPath }}{{ else }}/data{{ end }}
          resources:
            {{- toYaml .Values.console.resources | nindent 12 }}
      volumes:
        - name: mol-audit-data
          {{- if eq .Values.storage.type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ include "molecular-audit-core.fullname" . }}-data
          {{- else if eq .Values.storage.type "gcs" }}
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: {{ .Values.storage.gcs.bucket | quote }}
              implicitDirs: "true"
              "implicit-dirs": "true"
              mountOptions: "implicit-dirs"
              gcsfuseOptions: "implicit-dirs"
          {{- end }}
{{- end }}
