{{- if eq .Values.storage.type "pvc" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "molecular-audit-core.fullname" . }}-data
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molecular-audit-core.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size | quote }}
  storageClassName: {{ .Values.storage.pvc.storageClassName | quote }}
{{- end }}
