{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "molecular-audit-core.serviceAccountName" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molecular-audit-core.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.workloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gcpServiceAccount | quote }}
    {{- end }}
    {{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}
